### ISSUE TITLE
Problem Tobias

### ISSUE THREAD

**Issue by sirkrypt0** [compprog-lecture-tools/fun-contest-2023#15]
# Data Rate SLA

Your work as a network engineer at some large company which provides networking services to its customers. Currently, you have two data centers which are not connected directly, but rather through internet exchange points.

The links between the exchange points operate at certain data rates and may differ.

It just so happens, that some links fail or are affected by maintenance. However, you still want to provide a Service Level Agreement (SLA) to your customers, so you need to know the maximum data rate that you can achieve, if any link in the network fails.

## Input

- `n` the number of nodes (1 being your first data center, `n` being you second data center)
- `m` the number of links
- `m` lines containing the integers `a`, `b`, `r` representing the two connected nodes and the data rate at which the bidirectional link operates

## Output

Print the maximum data rate that can be achieved between your two centers if any link fails.

## Solution Idea

1. Calculate the overall MaxFlow as an upper bound.
2. For each edge in the MaxFlow, recompute the MaxFlow for the case that the edge fails.
3. Output the minimum over all max flows found.

The problem could be modified such that only the bottleneck edges fail (because they are stressed the most).

**Comment by roehrt** [comment]
Interesting problem! Out of personal curiosity: Do you know the name of the problem / any faster solution than "do it"?
"The problem could be modified such that only the bottleneck edges fail (because they are stressed the most)."
Could you clarify this modification?

**Comment by sirkrypt0** [comment]
> Do you know the name of the problem / any faster solution than "do it"?

This problem was described in [Maximizing residual flow under an arc destruction](https://onlinelibrary.wiley.com/doi/abs/10.1002/net.10001) by Aneja et al. who present an efficient solution in the paper and labeled it *the maximum residual flow problem*.
However, the problem is also called *Maximum Robust Flow* with k=1 in [The Complexity of Computing a Robust Flow](https://arxiv.org/pdf/1704.08241.pdf).

Is that what you had in mind?

> Could you clarify this modification?

This modification would basically only consider failure on edges that are part of the MinCut (and therefore bottleneck edges in the original MaxFlow).

**Comment by roehrt** [comment]
Yes, thank you! ^^
Regarding your possible modification: there might be multiple possible MaxFlows and MinCuts in general graphs and finding all edges that are part of a MinCut is not that trivial of a task.

**Comment by sirkrypt0** [comment]
> there might be multiple possible MaxFlows and MinCuts in general graphs and finding all edges that are part in one MinCut is not that trivial of a task.

Ah, that's true.

**Comment by roehrt** [comment]
Hey there, just a quick reminder that the deadline for your problem PR is on Friday. [If you are still searching for a possible modification: a typical modification would be to add some constraints like regularity or specific constraints on the weights to create a problem with increased limits that is only solvable through a clever observation. I. e. constructing a graph where for example the MinCut is trivially known, we see the heaviest edge is a lower bound for the solution and there might be (hidden by constraints) only 3 other edges with higher weight we need to check..]
