### ISSUE TITLE
Problem by Robert and Tobias

### ISSUE THREAD

**Issue by judgeNotFound** [compprog-lecture-tools/fun-contest-2023#25]
Problem:

One day, Christian, the CEO of _Super Arrangement Productions_, entered one of their offices
to talk to an employee who complained about the lack of motivation in their company. 
Christian was quite surprised, that not only the department, but the whole company was not motivated
at all.

That is why Christian made the decision to hire a motivation agency to send the best of their coaches
to help motivate the people again.

In a brief knowledge exchange with the head of the coaches, Christian learned the following things:

- Employees have to be motivated by coaches individually, but an employee will not allow getting motivated
       by a coach that their boss did not get motivated by.
- Employees are as motivated as the coach motivating them, after they got coached.
- Each employee has a demotivational level, which tells how much effort it needs for a coach to
       motivate the employee again.
- After being motivated again, employees are willing to motivate other employees, but only if those
       employees are directly or indirectly under their current position.
- Motivating employees is exhausting, which means that coaches and employees motivating other employees
       will be less motivated, equally to the level of demotivation.
- The agency sends their best coaches with each having a motivational level of 20.

Since Christian enforced saving measures, he wants to spend as little as possible. Therfore, as few coaches 
as possible should be sent. They will start working with Christian himself.

Even though the whole company should become motivated again, some people simply might not be motivatable.
Christian wants to know who these people are.

Input 

The input consists of three lines, describing a single test case.
The first line contains an integer n (1 <= n <= 10^5), the number of employees.
The second line contains n integers. The ith integer is mi (0 <= mi <= 20), the motivational level of employee i.
The third line contains n - 1 integers. The ith integer is bi+1 (1 <= bi+1 < i + 1), the direct boss of colleague i + 1.

Output

Firstly, output the minimal number of coaches required to motivate the company. Secondly, output the number of 
unmotivatable employees, followed by the numbers of those employees.

Solution Idea:

Using a Tree-DP should be sufficient. The solution for a leaf is trivial, and given the needed coaches for each subtree of an inner node, it is easy to calculate the solution for an inner node.

(Sorry being late on creating the issue for the PR)

**Comment by roehrt** [comment]
Hey, sorry that you didn't hear from us earlier. We read your problem statement but didn't communicated that we had no objections and you can start buildup -- that's on us, sorry again. We implicitly assumed that you wanted a review of your problem as a whole, i. e. with you generator + solution. Could you share a short formalized version of the problem with us? :)

**Comment by judgeNotFound** [comment]
@roehrt Sure thing, I added the solution + generator in the PR. Over the next few days, I will add more test cases.

A formalized way to look at the problem would the following:

```
Given a tree T, with each node having a weight w, find the minimal number of 
subjects to walk all paths that do not exceed the path length with a given 
threshold. All reachable nodes should be reached. At each path separation, 
the subjects have to decide for a specific path.
```

**Comment by roehrt** [comment]
So you want to cover a directed tree with minimum amount of paths with limited weight? And for testing purposes: Do you have the original problem or did you made the problem up yourselves?
