### ISSUE TITLE
Problem Lara & Johannes

### ISSUE THREAD

**Issue by johannes-poetzsch** [compprog-lecture-tools/fun-contest-2023#7]
### Problem:
Given an undirected Graph G (n ≤ 10^5, m ≤ 10^5) where each vertex represents one of n half-open (time) intervals with equal length and two vertices u and v are connected iff their corresponding intervals overlap, you are asked to find the chromatic number of G, that is the minimum amount of colors needed to paint each node without having two neighboring nodes of the same color. That is equivalent to outputting the maximum number of intervals overlapping at any point.

### Solution Idea:
Treat the problem like an interval problem: First find the first/last interval and then iterate over all intervals in order, while tracking the maximum amount of intervals that overlapped at any time so far.
First use BFS to find the first or last interval: Between the nodes that are found last, the one with the least edges either corresponds to the last/first interval, or if there are multiple such nodes, any one of them has the same overlaps as the first/last interval and is therefor equivalent to that node and can be used interchangeably.
Starting from that node, use a queue of nodes, that contains nodes that all overlap with each other to iterate over all intervals in order. The chromatic number can be determined by tracking the maximum size of that queue.

Inspired by:
Dörpinghaus, Jens. “Graphen und Graphenfärbungen”, Die Wurzel - Zeitschrift für Mathematik, vol. 47, September/October 2013, pp. 228-229

**Comment by schmidtjonas** [comment]
Nice problem

**Comment by schmidtjonas** [comment]
But I think your first step does not work like you state it: Consider the intervals 
(1,4), (3,7), (5,5), (6,8), (6,9). 
When starting the BFS from (1,4) you would pick the node (5,5) (it has distance 2 and degree 1), which is neither last nor first. Do you know how to fix this? 
Edit: nevermind, it works because your intervals have equal length.
